// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ipfxguvkqnudvvdzornp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlwZnhndXZrcW51ZHZ2ZHpvcm5wIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgzMzM4MjAsImV4cCI6MjA2MzkwOTgyMH0.RoJ38_s14IeOZlN-f-AfHdLl0PDDmJVlnMsn4NU3zJ8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);